### ISSUE TITLE
Just a static chart?

### ISSUE THREAD

**Issue by for-coursera** [keithknott26/datadash#7]
I'm probably missing something but can `datadash` produce just a simple static chart from some non-updating data? I mean, with no refresh, no stream, just drew a line given two columns of data? :)

**Comment by keithknott26** [comment]
Hello,

Thanks for your question --I believe  it depends on how many records in the dataset but you could try something like "./datadash tools/sampledata/5col-errors --seek-interval=1ms --redraw-interval=10s which should display the complete graph after 10s of seeking through the records 1ms at a time. 

Let me know if that works for you.

Thanks,
Keith

**Comment by for-coursera** [comment]
Thanks, @keithknott26!

That indeed was it :)

I'm closing this, but also one more question if you don't mind: when the data lies in some very narrow range, is it possible somehow to "expand" it vertically, to adapt the Y axis in such a way that the changes present in the data would become more obvious?

To illustrate what I mean, I'll add a screenshot showing how `datadash` plots it now: https://i.imgur.com/o5ghNgs.png

As you can see, the data fluctuates only between 22.77 and 23.37. However, if the Y axis would start not from 0 but 22, for instance, it would make the graph way more obvious :)

What do you think? Can fill a separate issue if you are interested :)

**Comment by keithknott26** [comment]
Hi @for-coursera,

Thanks for reaching out i'm glad the fix helped. There is an option to change the scaling on the Y axis, I'll work on getting this added as a feature or command line flag. 

`
// YAxisAdaptive makes the Y axis adapt its base value depending on the provided series.

// Without this option, the Y axis always starts at the zero value regardless of
// values available in the series.
// When this option is specified and the series don't contain value zero, the Y
// axis will be adapted to the minimum value for all-positive series or the
// maximum value for all-negative series. The Y axis still starts at the zero
// value if the series contain both positive and negative values.
func YAxisAdaptive() Option {
	return option(func(opts *options) {
		opts.yAxisMode = axes.YScaleModeAdaptive
	})
}
`

Thanks,
Keith

**Comment by keithknott26** [comment]
Hi @for-coursera ,

I've gone ahead and added the command line flag "-y" to enable the adaptive y-axis feature. Please download the latest changes and build again, also I've bumped some dependencies to the latest version so you'll want to run "go get -u ./..." in the base directory if the compiler complains.

Thanks,
Keith

**Comment by for-coursera** [comment]
@keithknott26 

Oh, that's an absolute beauty, thank you so much!

Certainly looks way, way better than gnuplot's `dumb` terminal I was using previously :)

  - https://i.imgur.com/ZxX8shB.png vs https://i.imgur.com/zKzV3BM.png
